# Generated by Django 6.0.5 on 2026-05-28 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=20)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.competence')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='developers.profil')),
            ],
            options={
                'unique_together': {('profil', 'competence')},
            },
        ),
    ]
